### PR TITLE
Fix Button styles when using `bg` and `color` props together

### LINKED ISSUE #255: Dropdown button doesn't behave as expected when setting color
When using the color prop on a `DropDownButton`, the color is not respected on hover.

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Fixes #255

change-type: patch

### CODE REVIEW

File: src/components/Button.tsx [hunk 1]
```diff
@@ -89,6 +89,13 @@ const Outline = Button.extend`
 		getColor(props, 'color', 'main') || props.theme.colors.text.main};
 	background: ${props => props.color || 'none'};
 	border: 1px solid;
+
+	&:hover,
+	&:focus,
+	&:active {
+		background-color: ${props => props.bg ?
+			darken(props.bg as string) : (getColor(props, 'bg', 'dark') || props.theme.colors.tertiary.dark)};
```
Comment (thgreasi) [inline src/components/Button.tsx]: What's the case that this fallback to the tertiary color is used?

Comment (LucianBuzzo) [reply src/components/Button.tsx]: This happens if you don't specify a primary / seconday or tertiary option. eg
```
<Button outline>button</Button>
```
