### PR TITLE
Fix bug where filters still get updated if cancel is pressed

### LINKED ISSUE #171: Filters: filters still get updated if cancel is pressed
See https://github.com/resin-io/resin-ui/issues/1517

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Fixes #171

change-type: patch

### CODE REVIEW

File: src/components/Filters/index.js [hunk 1]
```diff
@@ -261,14 +261,21 @@ class Filters extends React.Component {
...
+  }
+
   render () {
     const inputModels = sieve.makeFilterInputs(this.props.schema)
     const rules = this.props.rules || []
 
     return (
       <FilterWrapper mb={3}>
         <Flex justify='space-between'>
-          <Button primary onClick={() => this.toggleModal()}>
```
Comment (thgreasi) [inline src/components/Filters/index.js]: It seems that `toggleModal()` isn't used any more, can we drop it?

File: src/components/Filters/index.js [hunk 2]
```diff
@@ -261,14 +261,21 @@ class Filters extends React.Component {
     this.props.setViews(views)
   }
 
+  openNewFilterModal () {
```
Comment (thgreasi) [inline src/components/Filters/index.js]: Would it make sense to be names `showNewFilterModel` since we already have `showEditModal`?

File: src/components/Filters/index.js (hunk 1 above)
Comment (LucianBuzzo) [reply src/components/Filters/index.js]: Yep can do
